version: '3.8'

services:
  dev:
    container_name: meet.us
    image: meet.us:1.0.0
    build:
      context: .
      target: development
      dockerfile: ./Dockerfile
    command: yarn test:debug
    networks:
      - meet.us-network
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    ports:
      - 3000:3000
  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - '8081:80'
    networks:
      - meet.us-network
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
  db:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    networks:
      - meet.us-network
    environment:
      MYSQL_ROOT_PASSWORD: password

networks:
  meet.us-network:

volumes:
  db_data:
